#!/bin/sh
ENV_FILENAME="/app/.env"

# Create .env file
touch $ENV_FILENAME

# ETHEREUM env vars
echo "VITE_ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_EXPLORER_URL=$ETHEREUM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_BRIDGE_CONTRACT_ADDRESS=$ETHEREUM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=$ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT" >> $ENV_FILENAME
echo "VITE_ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=$ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS" >> $ENV_FILENAME

# POLYGON ZK EVM env vars
echo "VITE_POLYGON_ZK_EVM_RPC_URL=$POLYGON_ZK_EVM_RPC_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_EXPLORER_URL=$POLYGON_ZK_EVM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=$POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_NETWORK_ID=$POLYGON_ZK_EVM_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_CHAIN_ID=$POLYGON_ZK_EVM_CHAIN_ID" >> $ENV_FILENAME

# VIZING env vars
echo "VITE_VIZING_RPC_URL=$VIZING_RPC_URL" >> $ENV_FILENAME
echo "VITE_VIZING_EXPLORER_URL=$VIZING_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_VIZING_BRIDGE_CONTRACT_ADDRESS=$VIZING_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_VIZING_OMNI_CONTRACT_ADDRESS=$VIZING_OMNI_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_VIZING_NETWORK_ID=$VIZING_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_VIZING_CHAIN_ID=$VIZING_CHAIN_ID" >> $ENV_FILENAME

# ARBITRUM env vars
echo "VITE_ARBITRUM_RPC_URL=$ARBITRUM_RPC_URL" >> $ENV_FILENAME
echo "VITE_ARBITRUM_EXPLORER_URL=$ARBITRUM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_ARBITRUM_BRIDGE_CONTRACT_ADDRESS=$ARBITRUM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_ARBITRUM_NETWORK_ID=$ARBITRUM_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_ARBITRUM_CHAIN_ID=$ARBITRUM_CHAIN_ID" >> $ENV_FILENAME

# BASE env vars
echo "VITE_BASE_RPC_URL=$BASE_RPC_URL" >> $ENV_FILENAME
echo "VITE_BASE_EXPLORER_URL=$BASE_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_BASE_BRIDGE_CONTRACT_ADDRESS=$BASE_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_BASE_NETWORK_ID=$BASE_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_BASE_CHAIN_ID=$BASE_CHAIN_ID" >> $ENV_FILENAME

# OPTIMISM env vars
echo "VITE_OPTIMISM_RPC_URL=$OPTIMISM_RPC_URL" >> $ENV_FILENAME
echo "VITE_OPTIMISM_EXPLORER_URL=$OPTIMISM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_OPTIMISM_BRIDGE_CONTRACT_ADDRESS=$OPTIMISM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_OPTIMISM_NETWORK_ID=$OPTIMISM_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_OPTIMISM_CHAIN_ID=$OPTIMISM_CHAIN_ID" >> $ENV_FILENAME

# TAIKO env vars
echo "VITE_TAIKO_RPC_URL=$TAIKO_RPC_URL" >> $ENV_FILENAME
echo "VITE_TAIKO_EXPLORER_URL=$TAIKO_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_TAIKO_BRIDGE_CONTRACT_ADDRESS=$TAIKO_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_TAIKO_NETWORK_ID=$TAIKO_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_TAIKO_CHAIN_ID=$TAIKO_CHAIN_ID" >> $ENV_FILENAME

# LINEA env vars
echo "VITE_LINEA_RPC_URL=$LINEA_RPC_URL" >> $ENV_FILENAME
echo "VITE_LINEA_EXPLORER_URL=$LINEA_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_LINEA_BRIDGE_CONTRACT_ADDRESS=$LINEA_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_LINEA_NETWORK_ID=$LINEA_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_LINEA_CHAIN_ID=$LINEA_CHAIN_ID" >> $ENV_FILENAME

# SCROLL env vars
echo "VITE_SCROLL_RPC_URL=$SCROLL_RPC_URL" >> $ENV_FILENAME
echo "VITE_SCROLL_EXPLORER_URL=$SCROLL_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_SCROLL_BRIDGE_CONTRACT_ADDRESS=$SCROLL_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_SCROLL_NETWORK_ID=$SCROLL_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_SCROLL_CHAIN_ID=$SCROLL_CHAIN_ID" >> $ENV_FILENAME

# BLAST env vars
echo "VITE_BLAST_RPC_URL=$BLAST_RPC_URL" >> $ENV_FILENAME
echo "VITE_BLAST_EXPLORER_URL=$BLAST_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_BLAST_BRIDGE_CONTRACT_ADDRESS=$BLAST_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_BLAST_NETWORK_ID=$BLAST_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_BLAST_CHAIN_ID=$BLAST_CHAIN_ID" >> $ENV_FILENAME

# BOB env vars
echo "VITE_BOB_RPC_URL=$BOB_RPC_URL" >> $ENV_FILENAME
echo "VITE_BOB_EXPLORER_URL=$BOB_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_BOB_BRIDGE_CONTRACT_ADDRESS=$BOB_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_BOB_NETWORK_ID=$BOB_NETWORK_ID" >> $ENV_FILENAME
echo "VITE_BOB_CHAIN_ID=$BOB_CHAIN_ID" >> $ENV_FILENAME

# BRIDGE API env vars
echo "VITE_BRIDGE_API_URL=$BRIDGE_API_URL" >> $ENV_FILENAME

# FIAT EXCHANGE RATES API env vars
echo "VITE_ENABLE_FIAT_EXCHANGE_RATES=$ENABLE_FIAT_EXCHANGE_RATES" >> $ENV_FILENAME

if [ ! -z "$FIAT_EXCHANGE_RATES_API_URL" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_URL=$FIAT_EXCHANGE_RATES_API_URL" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_API_KEY" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_KEY=$FIAT_EXCHANGE_RATES_API_KEY" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS=$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" >> $ENV_FILENAME
fi

# OUTDATED NETWORK MODAL
echo "VITE_ENABLE_OUTDATED_NETWORK_MODAL=$ENABLE_OUTDATED_NETWORK_MODAL" >> $ENV_FILENAME

if [ ! -z "$OUTDATED_NETWORK_MODAL_TITLE" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_TITLE=$OUTDATED_NETWORK_MODAL_TITLE" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1=$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_1" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2=$OUTDATED_NETWORK_MODAL_MESSAGE_PARAGRAPH_2" >> $ENV_FILENAME
fi

if [ ! -z "$OUTDATED_NETWORK_MODAL_URL" ];
then
  echo "VITE_OUTDATED_NETWORK_MODAL_URL=$OUTDATED_NETWORK_MODAL_URL" >> $ENV_FILENAME
fi

# DEPOSIT WARNING
echo "VITE_ENABLE_DEPOSIT_WARNING=$ENABLE_DEPOSIT_WARNING" >> $ENV_FILENAME

# REPORT FORM
echo "VITE_ENABLE_REPORT_FORM=$ENABLE_REPORT_FORM" >> $ENV_FILENAME

if [ ! -z "$REPORT_FORM_URL" ];
then
  echo "VITE_REPORT_FORM_URL=$REPORT_FORM_URL" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_ERROR_ENTRY" ];
then
  echo "VITE_REPORT_FORM_ERROR_ENTRY=$REPORT_FORM_ERROR_ENTRY" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_PLATFORM_ENTRY" ];
then
  echo "VITE_REPORT_FORM_PLATFORM_ENTRY=$REPORT_FORM_PLATFORM_ENTRY" >> $ENV_FILENAME
fi

if [ ! -z "$REPORT_FORM_URL_ENTRY" ];
then
  echo "VITE_REPORT_FORM_URL_ENTRY=$REPORT_FORM_URL_ENTRY" >> $ENV_FILENAME
fi

echo "Generated .env file:"
echo "$(cat /app/.env)"

# Check if $ENV is set and not empty
if [ -n "$ENV" ]; then
  # Build app with the specified environment mode
  cd /app && npm run build -- --mode $ENV
else
  # Build app without specifying the environment mode
  cd /app && npm run build
fi

# Copy nginx config
cp /app/deployment/nginx.conf /etc/nginx/conf.d/default.conf

# Copy app dist
cp -r /app/dist/. /usr/share/nginx/html

# Delete source code
rm -rf /app

# Run nginx
nginx -g 'daemon off;'
