import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useDefaultBridgeDepositFormStyles = createUseStyles((theme: Theme) => ({
  amountInput: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: 8,
    // "&:disabled": {
    //   backgroundColor: "transparent",
    // },
    color: theme.palette.white.default,
    fontSize: "24px",
    fontWeight: 500,
    lineHeight: "24px",
    outline: "none",
    textAlign: "right",
    width: "100%",
    // [theme.breakpoints.upSm]: {
    //   fontSize: (value: number) => (value < 16 ? "40px" : "30px"),
    //   lineHeight: "40px",
    // },
  },
  card: {
    // marginBottom: 20,
    // padding: [theme.spacing(2), theme.spacing(3)],
  },
  chainIconWrap: {
    alignItems: "center",
    background: "#F3F3FA",
    borderRadius: "50%",
    display: "flex",
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  chainName: {
    color: theme.palette.white.default,
    fontSize: 16,
  },
  connectWalletButtonWrap: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
    height: 56,
    margin: [theme.spacing(4), "auto", 0],
    width: 560,
  },
  form: {
    // background: "pink",
    // border: '1px solid red',
    // borderRadius: 24,
    // height: 472,
    margin: "auto",
    // padding: [theme.spacing(3), theme.spacing(3)],
    // width: 608,
  },
  fromChain: {
    // "&:hover": {
    //   backgroundColor: theme.palette.grey.light,
    // },
    alignItems: "center",
    background: "none",
    border: "none",
    borderRadius: 8,
    // color: theme.palette.white.default,
    cursor: "pointer",
    display: "flex",
    gap: theme.spacing(0.5),
    // marginBottom: -theme.spacing(0.75),
    // marginLeft: -theme.spacing(1.25),
    // marginTop: theme.spacing(0.5),
    padding: [theme.spacing(0), 12],
    transition: theme.hoverTransition,
  },
  fromChainInfoRow: {
    borderBottom: "1px solid rgba(255, 255, 255, 0.2)",
    display: "flex",
    height: 56,
    padding: [theme.spacing(0), theme.spacing(2)],
    width: "100%",
  },
  fromChainTokenRow: {
    display: "flex",
    height: 80,
    padding: theme.spacing(2),
    width: "100%",
  },
  icons: {
    height: 20,
    width: 20,
    [theme.breakpoints.upSm]: {
      height: 24,
      width: 24,
    },
  },
  invalidInputMsg: {
    color: theme.palette.error.main,
    fontSize: 14,
    marginTop: 8,
  },
  leftBox: {
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  maxButton: {
    "&:hover": {
      cursor: "pointer",
    },
    alignItems: "center",
    color: theme.palette.themeRed,
    fontSize: 16,
    marginLeft: 8,
    opacity: "0.4",
  },
  middleRow: {
    borderTop: `1px solid ${theme.palette.grey.light}`,
    // marginTop: theme.spacing(1.25),
    // padding: [theme.spacing(2), 0, 0],
  },
  rightBox: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
  },
  spinner: {
    margin: "auto",
    marginTop: theme.spacing(7),
  },
  toChain: {
    alignItems: "center",
    background: "none",
    border: "none",
    borderRadius: 8,
    display: "flex",
    gap: theme.spacing(1),
    // marginBottom: -theme.spacing(0.75),
    // marginLeft: -theme.spacing(1.25),
    marginTop: theme.spacing(1.5),
    // padding: [theme.spacing(0), theme.spacing(1.25)],
    [theme.breakpoints.upSm]: {
      gap: theme.spacing(1.25),
    },
  },
  toChainCard: {
    marginTop: 20,
  },
  toChainIcon: {
    height: 32,
    width: 32,
  },
  toChainName: {
    fontSize: 20,
    fontWeight: 500,
  },
  toChainRow: {
    display: "flex",
    padding: [19, 16, 16],
  },
  toChainRowLeftBox: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  toChainRowRightBox: {
    alignItems: "flex-end",
    color: theme.palette.white.default,
    display: "flex",
    flex: 1,
    flexDirection: "column",
    fontSize: 24,
    fontWeight: 500,
    justifyContent: "flex-end",
  },
  tokenName: {
    color: theme.palette.white.default,
  },
  tokenSelector: {
    alignItems: "center",
    backgroundColor: "rgba(154, 154, 154, 0.12)",
    border: "none",
    borderRadius: 12,
    cursor: "pointer",
    display: "flex",
    gap: theme.spacing(1),
    padding: [theme.spacing(1), theme.spacing(1.75), theme.spacing(1), theme.spacing(1)],
    transition: theme.hoverTransition,
    // [theme.breakpoints.upSm]: {
    //   backgroundColor: theme.palette.grey.light,
    //   gap: theme.spacing(2),
    //   padding: [theme.spacing(1.5), theme.spacing(2)],
    // },
  },
  txMsgBox: {},
  txMsgText: {
    color: theme.palette.white.transparency60,
    margin: 0,
  },
  txMsgTitle: {
    color: theme.palette.white.default,
    marginBottom: theme.spacing(1),
    marginTop: 0,
  },
}));
